test:
  stage: test
  script:
    - cd project
    - bundle install
    - rails db:migrate RAILS_ENV=test
    - yarn
    - rails webpacker:compile
    - PARALLEL_WORKERS=1 rails test
  only:
    - project

deploy:
  stage: deploy
  script:
    - pumactl stop -P ~/blog4/tmp/pids/server.pid || true
    - rsync -arv --delete ./blog4 ~
    - cd ~/project
    - bundle install
    - rails db:migrate
    - yarn
    - rails webpacker:compile
    - rails server -d -b 0.0.0.0 -p 5000
  only:
    - project

